project_id  = "rd-15112022"
file_name = "source.zip"
bucket_name= "rd-search"
function_name = "cloud_function_demo_for_test"
function_description = "function that print values from csv file"
function_run_time = "python39"
available_memory_mb = 128
f_entry_point = "cloud_function_demo"
cf_region= "europe-west1"
